DEFAULT_RANDOM_SEED = 42
DEFAULT_N_SAMPLES = 500
DEFAULT_TEST_SIZE = 0.3
DEFAULT_DECISION_THRESHOLD = 0.5

DEFAULT_GROUP_PROPORTION = 0.5   # Anteil gender=1
DEFAULT_LABEL_BIAS_STRENGTH = 0.0
DEFAULT_IMBALANCE_TARGET = None
